### ISSUE TITLE
ERROR REQ-1 Could not find browser revision latest

### ISSUE THREAD

**Issue by janot** [ngosang/FlareSolverr#2]
Ubuntu 20.04

2020-06-22T08:30:24.191Z INFO REQ-1 Incoming request: POST /v1
2020-06-22T08:30:24.205Z INFO REQ-1 Params: {"method":"GET","url":"https://www.bteye.org/q/test","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0","maxTimeout":60000}
2020-06-22T08:30:24.269Z ERROR REQ-1 Could not find browser revision latest. Run "npm install" or "yarn install" to download a browser binary.

2020-06-22 01:30:24 	Error 	

{0} Jackett.Common.IndexerException: Exception (bteye): Could not find browser revision latest. Run "npm install" or "yarn install" to download a browser binary.
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Could not find browser revision latest. Run "npm install" or "yarn install" to download a browser binary.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 230
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224

**Comment by ngosang** [comment]
You need to set the environment variable `export PUPPETEER_PRODUCT=firefox` before running `npm install`. This can be done in one line `PUPPETEER_PRODUCT=firefox npm install`

**Comment by janot** [comment]
sorry if I misunderstand smth, that's how I'm running it while getting this error:

```
$ PUPPETEER_PRODUCT=firefox npm install
audited 70 packages in 3.54s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
$ node index.js
2020-06-22T08:44:24.644Z INFO REQ-0 FlareSolverr v1.0.0 listening on http://0.0.0.0:8191
2020-06-22T08:45:07.250Z INFO REQ-1 Incoming request: POST /v1
2020-06-22T08:45:07.256Z INFO REQ-1 Params: {"method":"GET","url":"https://www.bteye.org/q/test","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0","maxTimeout":60000}
2020-06-22T08:45:07.309Z ERROR REQ-1 Could not find browser revision latest. Run "npm install" or "yarn install" to download a browser binary.
```

**Comment by ngosang** [comment]
Humm, try to remove the `node_modules` folder. When I install the first time I can see this:
```
$ PUPPETEER_PRODUCT=firefox npm install

> puppeteer@3.3.0 install /home/vvv/workspace/FlareSolverr/node_modules/puppeteer
> node install.js

Requesting latest Firefox Nightly version from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central
Downloading Firefox Nightly r79.0a1 - 75.8 Mb [====================] 100% 0.0s 
```

**Comment by janot** [comment]
Now it is Firefox too and error is gone, I probably messed up somewhere when installing
